baseURL = 'https://servedsmart.com/'
title = 'Served Smart'

#languageCode = 'en-us'
defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true

pagination.pagerSize = 5
theme = 'beautifulhugo'

enableRobotsTXT = true

buildDrafts = false
buildFuture = false
buildExpired = false

# See: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true

enableGitInfo = true
