[[main]]
identifier = 'dienstleistungen'
name = 'Dienstleistungen'
pageRef = '/pages/services/'
weight = 10

[[main]]
identifier = 'beiträge'
name = 'Beiträge'
pageRef = '/'
weight = 20

[[main]]
identifier = 'impressum'
name = 'Impressum'
pageRef = '/pages/about-us/'
weight = 90
