[[main]]
identifier = 'search'
name = 'Search'
pageRef = '/search/'
weight = 10

[[main]]
identifier = 'services'
name = 'Services'
pageRef = '/services/'
weight = 20

[[main]]
identifier = 'posts'
name = 'Posts'
pageRef = '/posts/'
weight = 30

[[main]]
identifier = 'legal disclosure'
name = 'Legal Disclosure'
pageRef = '/terms/impressum/'
weight = 90
