[[main]]
identifier = 'suche'
name = 'Suche'
pageRef = '/search/'
weight = 10

[[main]]
identifier = 'dienstleistungen'
name = 'Dienstleistungen'
pageRef = '/posts/services/'
weight = 10

[[main]]
identifier = 'beiträge'
name = 'Beiträge'
pageRef = '/posts/'
weight = 20

[[main]]
identifier = 'archiv'
name = 'Archiv'
pageRef = '/archives/'
weight = 30

[[main]]
identifier = 'impressum'
name = 'Impressum'
pageRef = '/pages/impressum/'
weight = 90
