[[main]]
identifier = 'services'
name = 'Services'
pageRef = '/pages/services/'
weight = 10

[[main]]
identifier = 'posts'
name = 'Posts'
pageRef = '/posts/'
weight = 20

[[main]]
identifier = 'legal disclosure'
name = 'Legal Disclosure'
pageRef = '/pages/impressum/'
weight = 90
