[[main]]
identifier = 'services'
name = 'Services'
pageRef = '/services/'
weight = 10

[[main]]
identifier = 'posts'
name = 'Posts'
pageRef = '/posts/'
weight = 20

[[main]]
identifier = 'about us'
name = 'About Us'
pageRef = '/about-us/'
weight = 90
