[[main]]
identifier = 'dienstleistungen'
name = 'Dienstleistungen'
pageRef = '/services/'
weight = 10

[[main]]
identifier = 'beiträge'
name = 'Beiträge'
pageRef = '/posts/'
weight = 20

[[main]]
identifier = 'impressum'
name = 'Impressum'
pageRef = '/about-us/'
weight = 90
